### PR TITLE
add Spark RAPIDS Dataproc lab

### PR DESCRIPTION
**Pull request by mengdong**
add Spark RAPIDS Dataproc lab

### CODE REVIEW

**Comment by velascoluis** [comment]
Hi @mengdong , thank you so much for this PR, would it be possible to bootstrap the infra deployment with terraform?

Some examples here:

https://github.com/GoogleCloudPlatform/datalake-modernization-workshops/tree/main/s8s-spark-mlops/00-env-setup/terraform 

https://github.com/GoogleCloudPlatform/datalake-modernization-workshops/tree/main/hive-to-bq-biglake/src/terraform 

https://github.com/GoogleCloudPlatform/datalake-modernization-workshops/blob/main/admin-usecase/02-execution-instructions/terraform-execution.md 

And for dataproc on GCE, specifically: https://github.com/anagha-google/dataproc-labs (lab #2)

Thanks again

**Comment by mengdong** [comment]
Thanks @velascoluis  for your review! The infra is only cluster creation, do we still need to use terraform? I can do if it is a must.

**Comment by mengdong** [comment]
@velascoluis ping again on the question above, looking to having this merge asap, thanks!

**Comment by velascoluis** [comment]
Hi @mengdong not a must, just a nice to have. Will merge and open an issue for TF automation, feel free to take it :) Thanks again for your contrib

**Pull request merged**
